# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.1


### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [2]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

In [3]:
import numpy as np
lista = list(range(1000000))
vetor = np.arange(1000000)

%time for _ in range(5): vetor1 = vetor * 2 

%time for _ in range(5): lista2 = [x * 2 for x in lista]
    

Wall time: 11 ms
Wall time: 599 ms


### Exercício 2

In [7]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [16]:
vetor3 = np.array([0,1,2,3,4,5,6,7,8,9])
vetor3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
vetor3[5:8] = 0
vetor3

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

### Exercício 3

In [18]:
# Crie um array de 3 dimensões e imprima a dimensão 1 

In [24]:
matriz = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
matriz.ndim

3

In [26]:
matriz[0,0]

array([1, 2, 3])

### Exercício 4

In [27]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

In [38]:
matriz2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
matriz2.ndim

2

In [41]:
matriz2[2]


array([7, 8, 9])

In [47]:
matriz2[:2, 1:]

array([[2, 3],
       [5, 6]])

### Exercício 5

In [44]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
np.array(arr).T


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [57]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [61]:
for a,b,c in zip(xarr,yarr,cond):
    print(a,b,c)

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


In [65]:
res = [(a if c else b) for a, b, c in zip(xarr, yarr, cond)]
res

[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [66]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

In [67]:
A = np.array([[1,2,3,4,5,6,7,8]])
A

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [68]:
salva = np.save('array.npy', A)

In [69]:
B = np.load('array.npy')
B

array([[1, 2, 3, 4, 5, 6, 7, 8]])

### Exercício 8

In [70]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [72]:
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [73]:
print(list(dict.fromkeys(obj)))
#print(list(set(obj)))

['c', 'a', 'd', 'b']

### Exercício 9

In [89]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [90]:
arq = resp.json()

'BUG: CategoricalIndex.get_indexer issue with NaNs (#45361)'

In [94]:
dataset = pd.DataFrame(arq, columns =['number', 'title', 'labels', 'state'])
dataset

number                                              title  \
0    45373  BUG: CategoricalIndex.get_indexer issue with N...   
1    45372  BUG:  Pandas.DataFrame.str.replace function fa...   
2    45371  PERF: avoid SQL MetaData reflection in init #4...   
3    45370   DOC: add version dropdown to the online doc site   
4    45369  BUG: DataFrame constructor with copy=False and...   
5    45364  CI/TST: update pyarrow pin in windows-3.8 env ...   
6    45363  BUG: correctly instantiate subclassed DataFram...   
7    45362              BUG: CategoricalIndex.union with nans   
8    45361            BUG: CategoricalIndex.get_indexer with    
9    45360  BUG: No error raised in to_stata() for -np.inf...   
10   45359  BUG: categorical-with-nas to float64 instead o...   
11   45358  ENH: sorted numpy array of datetime64 as panda...   
12   45357  DEPR: DatetimeIndex.intersection with mixed ti...   
13   45353    REF: use standard coerce pattern in Block.shift   
14   45352  BUG: df.iloc[:, 0] = df.iloc[::-1, 0] not sett...   
15   45350  BUG: No error raised when write dta files usin...   
16   45349  ENH: ExtensionDtpye._dtype_with_na/_maybe_promote   
17   45348                           REF: Share Block.setitem   
18   45347                                  Update cheatsheet   
19   45346                         Ko ya346/update import doc   
20   45345                 is_numeric_dtype('B') returns True   
21   45344  TST: error in parquet tests on windows with ne...   
22   45343  Backport PR #45334 on branch 1.4.x (DEPR: un-d...   
23   45341                         ENH: add dtype to read_xml   
24   45339  DEPR: SparseArray.astype(dtype) respect non-sp...   
25   45337  BUG: read_fwf doesn't allow names with colspec...   
26   45333  DEPR: df.iloc[:, foo] = bar attempt to set inp...   
27   45332        ENH: fill_na with new fill_partial argument   
28   45331                                   TYP: offsets.pyi   
29   45328              BUG: accessor can't access `__name__`   

                                               labels state  
0   [{'id': 78527356, 'node_id': 'MDU6TGFiZWw3ODUy...  open  
1   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
2                                                  []  open  
3   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
4   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
5   [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
6   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
7                                                  []  open  
8   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
9   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
10                                                 []  open  
11  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
12  [{'id': 60458168, 'node_id': 'MDU6TGFiZWw2MDQ1...  open  
13                                                 []  open  
14                                                 []  open  
15  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
16  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
17                                                 []  open  
18                                                 []  open  
19                                                 []  open  
20  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
21  [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
22  [{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
23  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
24                                                 []  open  
25  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
26                                                 []  open  
27  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
28  [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
29  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open

### Exercício 10

In [ ]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

In [95]:
import sqlite3
import pandas as pd
query = """
CREATE TABLE CLIENTE
(Nome VARCHAR(50),
 cpf INTEGER(11),
 endereco VARCHAR(50),
 telefone VARCHAR(16)
 ); """

con = sqlite3.connect('exercicio.db')
con.execute(query)
con.commit()

In [96]:
data = [('Daniel', '48562357894', 'Rua sdsdds', '(16) 39545599'),
        ('Cintia', '48362357894', 'Rua sdsdds', '(16) 55685599'),
        ('Everson', '48562358884', 'Rua eerrds', '(16) 39547889')]
stmt = 'INSERT INTO CLIENTE VALUES(?,?,?,?)'
con.executemany(stmt, data)
con.commit()

In [98]:
cursor = con.execute('select * from cliente')
rows = cursor.fetchall()
rows

[('Daniel', 48562357894, 'Rua sdsdds', '(16) 39545599'),
 ('Cintia', 48362357894, 'Rua sdsdds', '(16) 55685599'),
 ('Everson', 48562358884, 'Rua eerrds', '(16) 39547889')]

In [99]:
cursor.description

(('Nome', None, None, None, None, None, None),
 ('cpf', None, None, None, None, None, None),
 ('endereco', None, None, None, None, None, None),
 ('telefone', None, None, None, None, None, None))

In [100]:
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

Nome          cpf    endereco       telefone
0   Daniel  48562357894  Rua sdsdds  (16) 39545599
1   Cintia  48362357894  Rua sdsdds  (16) 55685599
2  Everson  48562358884  Rua eerrds  (16) 39547889

# Fim


### Obrigado

### Visite o Blog da Data Science Academy - <a href="http://blog.dsacademy.com.br">Blog DSA</a>
